services:
  - type: web
    name: sleep-cbti-api
    env: node
    region: singapore
    plan: free
    buildCommand: cd server && npm ci && cd ../client && npm ci && npm run build
    startCommand: cd server && node src/index.js
    envVars:
      - key: DATABASE_URL
        value: mysql://root:JPWcejDnjFAIlpMqqcQzhUfgWnHLgySo@nozomi.proxy.rlwy.net:27964/railway
      - key: JWT_SECRET
        value: sleep-cbti-jwt-secret-2026
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
